apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: mailpit
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mailpit
  name: mailpit
