version: "3.8"

networks:
  workspace-network:

services:
  app:
    image: mcr.microsoft.com/devcontainers/base:jammy
    volumes:
      - ..:/workspace:cached
    networks:
      - workspace-network
    command: sleep infinity

  c4model:
    image: structurizr/lite
    ports:
      - "8080:8080"
    networks:
      - workspace-network
    volumes:
      - ../workspace.dsl:/usr/local/structurizr/workspace.dsl:ro

