apiVersion: v1
kind: Pod
metadata:
  name: quick-start
  namespace: demo
  labels:
    azure.workload.identity/use: "true"
spec:
  automountServiceAccountToken: false
  serviceAccountName: workload-identity-sa
  containers:
    - image: ghcr.io/azure/azure-workload-identity/msal-go
      name: oidc
      env:
        - name: KEYVAULT_URL
          value: https://kv-launchpad-dev-sea-01.vault.azure.net/
        - name: SECRET_NAME
          value: Saleor-Secret-Key
      resources:
        limits:
          cpu: 500m
          ephemeral-storage: 100Mi
          memory: 512Mi
        requests:
          cpu: 100m
          ephemeral-storage: 50Mi
          memory: 256Mi
