apiVersion: batch/v1
kind: Job
metadata:
  name: saleor-populatedb-job
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: populate-job
        app.kubernetes.io/instance: saleor-populatedb-job
        app.kubernetes.io/managed-by: Kustomize
        app.kubernetes.io/name: saleor
    spec:
      automountServiceAccountToken: false
      restartPolicy: Never
      serviceAccountName: saleor
      containers:
        - name: saleor-populatedb-job
          image: ghcr.io/saleor/saleor:latest
          command: ["python", "manage.py", "populatedb", "--createsuperuser"]
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-key
                  name: saleor-secrets
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-password
                  name: saleor-secrets
            - name: DATABASE_URL
              value: postgres://saleor:$(DATABASE_PASSWORD)@postgresql-hl.data-postgresql.svc.cluster.local:5432/saleor
          resources:
            limits:
              cpu: "1"
              ephemeral-storage: 1024Mi
              memory: 1Gi
            requests:
              cpu: 100m
              ephemeral-storage: 50Mi
              memory: 256Mi
          volumeMounts:
            - mountPath: /app/media
              name: saleor-media
      volumes:
        - name: saleor-media
          persistentVolumeClaim:
            claimName: saleor-media
