resources:
  # Data
  - "../../base/data/redis"
  - "../../base/data/postgresql"
  # Networking
  - "../../base/network/cert-manager"
  # Observibility
  - "../../base/observibility/jaeger"
  # Application
  - "../../base/app/mailpit"
  - "../../base/app/saleor"

patches:
  # Delete unused kind
  - path: ./patches/delete-spc.yml
    target:
      kind: SecretProviderClass
  - path: ./patches/delete-virtualservice.yml
    target:
      kind: VirtualService
  # Redis
  - path: ./patches/data/redis/remove-csi.yml
  # PostgreSQL
  - path: ./patches/data/postgresql/remove-csi.yml
  # Saleor
  - path: ./patches/app/saleor/remove-csi.yml

configMapGenerator:
  - name: common-config
    namespace: app-saleor
    literals:
      - DEFAULT_CHANNEL_SLUG=default-channel
      - HTTP_IP_FILTER_ALLOW_LOOPBACK_IPS=True
      - HTTP_IP_FILTER_ENABLED=True
      - DEFAULT_FROM_EMAIL=noreply@example.com

secretGenerator:
  - name: redis-secrets
    namespace: data-redis
    literals:
      - redis-password=changeit
  - name: postgresql-secrets
    namespace: data-postgresql
    literals:
      - postgres-password=changeit
      - password=changeit
  - name: mailpit-secrets
    namespace: app-mailpit
    literals:
      - ui.htpasswd=saleor:changeit
  - name: saleor-secrets
    namespace: app-saleor
    literals:
      - secret-key=changeit
      - redis-password=changeit
      - postgresql-password=changeit
